"""Route definitions with Python 3.14 template string support.

Example:
    GET_CONTACT = Route[None, ContactDetails](
        template=t"/{id}",
        response_model=ContactDetails,
    )

    bound = GET_CONTACT.bind(id="123")
    print(bound.url)  # "/{id}" interpolated to "/123"
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class Route:
    """
    Attributes:
        method: HTTP method
        template: Path
        request_model: Pydantic model for request body, or None
        response_model: Pydantic model for response
        params: Bound path parameters
    """

    method: str
    path: str
    request_model: type | None = None
    response_model: type | None = None
    params: dict[str, str] = field(default_factory=dict)

    @property
    def url(self) -> str:
        """Return interpolated path."""
        return self.path.format(**self.params)


SCHEMA = {
    "ACCOUNT": {
        "DELETE_PAYMENTSOURCE": Route("DELETE", "/account/paymentsource/{sourceId}", None, None, {}),
        "GET_PROFILE": Route("GET", "/account/profile", None, None, {}),
        "GET_VERIFYRESETTOKEN": Route("GET", "/account/verifyresettoken", None, None, {}),
        "POST_CONFIRM": Route("POST", "/account/confirm", "ConfirmEmailModel", None, {}),
        "POST_FORGOT": Route("POST", "/account/forgot", "ForgotLoginModel", None, {}),
        "POST_REGISTER": Route("POST", "/account/register", "RegistrationModel", None, {}),
        "POST_RESETPASSWORD": Route("POST", "/account/resetpassword", "ResetPasswordModel", None, {}),
        "POST_SEND_CONFIRMATION": Route("POST", "/account/sendConfirmation", None, None, {}),
        "POST_SETPASSWORD": Route("POST", "/account/setpassword", "ChangePasswordModel", None, {}),
        "PUT_PAYMENTSOURCE": Route("PUT", "/account/paymentsource/{sourceId}", None, None, {}),
    },
    "ADDRESS": {
        "GET_ISVALID": Route("GET", "/address/isvalid", None, "AddressIsValidResult", {}),
        "GET_PROPERTYTYPE": Route("GET", "/address/propertytype", None, "PropertyType", {}),
        "POST_AVOID_VALIDATION": Route("POST", "/address/{addressId}/avoidValidation", None, None, {}),
        "POST_VALIDATED": Route("POST", "/address/{addressId}/validated", "SaveValidatedRequest", None, {}),
    },
    "ADMIN": {
        "DELETE_ADVANCEDSETTINGS": Route("DELETE", "/admin/advancedsettings/{id}", None, None, {}),
        "GET_ADVANCEDSETTINGS": Route("GET", "/admin/advancedsettings/{id}", None, None, {}),
        "GET_ADVANCEDSETTINGS_ALL": Route("GET", "/admin/advancedsettings/all", None, None, {}),
        "GET_CARRIERERRORMESSAGE_ALL": Route("GET", "/admin/carriererrormessage/all", None, None, {}),
        "GET_GLOBALSETTINGS_COMPANYHIERARCHY": Route("GET", "/admin/globalsettings/companyhierarchy", None, "CompanyHierarchyInfo", {}),
        "GET_GLOBALSETTINGS_COMPANYHIERARCHY_COMPANY": Route("GET", "/admin/globalsettings/companyhierarchy/company/{companyId}", None, "CompanyHierarchyInfo", {}),
        "POST_ADVANCEDSETTINGS": Route("POST", "/admin/advancedsettings", "AdvancedSettingsEntitySaveModel", None, {}),
        "POST_CARRIERERRORMESSAGE": Route("POST", "/admin/carriererrormessage", "CarrierErrorMessage", None, {}),
        "POST_GLOBALSETTINGS_APPROVEINSURANCEEXCEPTION": Route("POST", "/admin/globalsettings/approveinsuranceexception", None, None, {}),
        "POST_GLOBALSETTINGS_GETINSURANCEEXCEPTIONS": Route("POST", "/admin/globalsettings/getinsuranceexceptions", "WebApiDataSourceLoadOptions", "List[SelectApproveInsuranceResult]", {}),
        "POST_GLOBALSETTINGS_INTACCT": Route("POST", "/admin/globalsettings/intacct", "WebApiDataSourceLoadOptions", None, {}),
        "POST_LOGBUFFER_FLUSH": Route("POST", "/admin/logbuffer/flush", None, None, {}),
        "POST_LOGBUFFER_FLUSH_ALL": Route("POST", "/admin/logbuffer/flushAll", None, None, {}),
    },
    "COMMODITY": {
        "GET": Route("GET", "/commodity/{id}", None, "CommodityWithParentsServiceResponse", {}),
        "POST": Route("POST", "/commodity", "AddCommodityModel", "CommodityServiceResponse", {}),
        "POST_SEARCH": Route("POST", "/commodity/search", "WebApiDataSourceLoadOptions", "List[CommodityDetails]", {}),
        "POST_SUGGESTIONS": Route("POST", "/commodity/suggestions", "GetCommoditySuggestionsDataSourceLoadOptions", "List[CommodityWithParents]", {}),
        "PUT": Route("PUT", "/commodity/{id}", "UpdateCommodityModel", "CommodityServiceResponse", {}),
    },
    "COMMODITY_MAP": {
        "DELETE": Route("DELETE", "/commodity-map/{id}", None, "ServiceBaseResponse", {}),
        "GET": Route("GET", "/commodity-map/{id}", None, "CommodityMapDetailsServiceResponse", {}),
        "POST": Route("POST", "/commodity-map", "AddCommodityMapModel", "CommodityMapServiceResponse", {}),
        "POST_SEARCH": Route("POST", "/commodity-map/search", "WebApiDataSourceLoadOptions", "List[CommodityMapDetails]", {}),
        "PUT": Route("PUT", "/commodity-map/{id}", "UpdateCommodityMapModel", "CommodityMapServiceResponse", {}),
    },
    "COMPANIES": {
        "GET": Route("GET", "/companies/{id}", None, None, {}),
        "GET_AVAILABLE_BY_CURRENT_USER": Route("GET", "/companies/availableByCurrentUser", None, None, {}),
        "GET_BRANDS": Route("GET", "/companies/brands", None, None, {}),
        "GET_BRANDSTREE": Route("GET", "/companies/brandstree", None, None, {}),
        "GET_CAPABILITIES": Route("GET", "/companies/{companyId}/capabilities", None, None, {}),
        "GET_CARRIER_ACOUNTS": Route("GET", "/companies/{companyId}/carrierAcounts", None, None, {}),
        "GET_DETAILS": Route("GET", "/companies/{companyId}/details", None, None, {}),
        "GET_FRANCHISEE_ADDRESSES": Route("GET", "/companies/{companyId}/franchiseeAddresses", None, "List[CompanyAddressInfo]", {}),
        "GET_FULLDETAILS": Route("GET", "/companies/{companyId}/fulldetails", None, "CompanyDetails", {}),
        "GET_GEOSETTINGS": Route("GET", "/companies/geosettings", None, None, {}),
        "GET_GEO_AREA_COMPANIES": Route("GET", "/companies/geoAreaCompanies", None, None, {}),
        "GET_INFO_FROM_KEY": Route("GET", "/companies/infoFromKey", None, None, {}),
        "GET_INHERITEDPACKAGINGLABOR": Route("GET", "/companies/{companyId}/inheritedpackaginglabor", None, None, {}),
        "GET_INHERITED_PACKAGING_TARIFFS": Route("GET", "/companies/{companyId}/inheritedPackagingTariffs", None, None, {}),
        "GET_PACKAGINGLABOR": Route("GET", "/companies/{companyId}/packaginglabor", None, None, {}),
        "GET_PACKAGINGSETTINGS": Route("GET", "/companies/{companyId}/packagingsettings", None, None, {}),
        "GET_SEARCH": Route("GET", "/companies/search", None, None, {}),
        "GET_SEARCH_CARRIER_ACCOUNTS": Route("GET", "/companies/search/carrier-accounts", None, None, {}),
        "GET_SUGGEST_CARRIERS": Route("GET", "/companies/suggest-carriers", None, "List[CarrierCompanyInfo]", {}),
        "POST_CAPABILITIES": Route("POST", "/companies/{companyId}/capabilities", "CommercialCapabilities", None, {}),
        "POST_CARRIER_ACOUNTS": Route("POST", "/companies/{companyId}/carrierAcounts", "UpdateCarrierAccountsModel", None, {}),
        "POST_FILTERED_CUSTOMERS": Route("POST", "/companies/filteredCustomers", "WebApiDataSourceLoadOptions", None, {}),
        "POST_FULLDETAILS": Route("POST", "/companies/fulldetails", "CompanyDetails", None, {}),
        "POST_GEOSETTINGS": Route("POST", "/companies/{companyId}/geosettings", "SaveGeoSettingModel", None, {}),
        "POST_LIST": Route("POST", "/companies/list", "TagBoxDataSourceLoadOptions", None, {}),
        "POST_PACKAGINGLABOR": Route("POST", "/companies/{companyId}/packaginglabor", "PackagingLaborSettings", None, {}),
        "POST_PACKAGINGSETTINGS": Route("POST", "/companies/{companyId}/packagingsettings", "PackagingTariffSettings", None, {}),
        "POST_SEARCH_V2": Route("POST", "/companies/search/v2", "SearchCompanyDataSourceLoadOptions", "List[SearchCompanyResponse]", {}),
        "POST_SIMPLELIST": Route("POST", "/companies/simplelist", "TagBoxDataSourceLoadOptions", None, {}),
        "PUT_FULLDETAILS": Route("PUT", "/companies/{companyId}/fulldetails", "CompanyDetails", "CompanyDetails", {}),
    },
    "COMPANY": {
        "DELETE_ACCOUNTS_STRIPE": Route("DELETE", "/company/{companyId}/accounts/stripe", None, None, {}),
        "DELETE_CONTAINERTHICKNESSINCHES": Route("DELETE", "/company/{companyId}/containerthicknessinches", None, None, {}),
        "DELETE_MATERIAL": Route("DELETE", "/company/{companyId}/material/{materialId}", None, None, {}),
        "DELETE_TRUCK": Route("DELETE", "/company/{companyId}/truck/{truckId}", None, "ServiceWarningResponse", {}),
        "GET_ACCOUNTS_STRIPE_CONNECTURL": Route("GET", "/company/{companyId}/accounts/stripe/connecturl", None, None, {}),
        "GET_CALENDAR": Route("GET", "/company/{companyId}/calendar/{date}", None, "Calendar", {}),
        "GET_CALENDAR_BASEINFO": Route("GET", "/company/{companyId}/calendar/{date}/baseinfo", None, "BaseInfoCalendar", {}),
        "GET_CALENDAR_ENDOFDAY": Route("GET", "/company/{companyId}/calendar/{date}/endofday", None, None, {}),
        "GET_CALENDAR_STARTOFDAY": Route("GET", "/company/{companyId}/calendar/{date}/startofday", None, None, {}),
        "GET_CONTAINERTHICKNESSINCHES": Route("GET", "/company/{companyId}/containerthicknessinches", None, "List[ContainerThickness]", {}),
        "GET_GRIDSETTINGS": Route("GET", "/company/{companyId}/gridsettings", None, "GridSettingsEntity", {}),
        "GET_MATERIAL": Route("GET", "/company/{companyId}/material", None, "List[CompanyMaterial]", {}),
        "GET_PLANNER": Route("GET", "/company/{companyId}/planner", None, "List[PlannerTask]", {}),
        "GET_SETUPDATA": Route("GET", "/company/{companyId}/setupdata", None, "CompanySetupData", {}),
        "GET_TRUCK": Route("GET", "/company/{companyId}/truck", None, "List[Truck]", {}),
        "POST_ACCOUNTS_STRIPE_COMPLETECONNECTION": Route("POST", "/company/{companyId}/accounts/stripe/completeconnection", None, None, {}),
        "POST_CONTAINERTHICKNESSINCHES": Route("POST", "/company/{companyId}/containerthicknessinches", "ContainerThickness", None, {}),
        "POST_GRIDSETTINGS": Route("POST", "/company/{companyId}/gridsettings", "SaveGridSettingsModel", None, {}),
        "POST_MATERIAL": Route("POST", "/company/{companyId}/material", "SaveCompanyMaterialModel", "CompanyMaterial", {}),
        "POST_TRUCK": Route("POST", "/company/{companyId}/truck", "SaveTruckRequest", "SaveEntityResponse", {}),
        "PUT_MATERIAL": Route("PUT", "/company/{companyId}/material/{materialId}", "SaveCompanyMaterialModel", "CompanyMaterial", {}),
        "PUT_TRUCK": Route("PUT", "/company/{companyId}/truck/{truckId}", "SaveTruckRequest", "SaveEntityResponse", {}),
    },
    "CONTACTS": {
        "GET": Route("GET", "/contacts/{id}", None, None, {}),
        "GET_EDITDETAILS": Route("GET", "/contacts/{contactId}/editdetails", None, "ContactDetailedInfo", {}),
        "GET_HISTORY_AGGREGATED": Route("GET", "/contacts/{contactId}/history/aggregated", None, "ContactHistoryAggregatedCost", {}),
        "GET_HISTORY_GRAPHDATA": Route("GET", "/contacts/{contactId}/history/graphdata", None, "ContactHistoryGraphData", {}),
        "GET_PRIMARYDETAILS": Route("GET", "/contacts/{contactId}/primarydetails", None, "ContactPrimaryDetails", {}),
        "GET_USER": Route("GET", "/contacts/user", None, None, {}),
        "POST_CUSTOMERS": Route("POST", "/contacts/customers", "SearchContactRequest", None, {}),
        "POST_EDITDETAILS": Route("POST", "/contacts/editdetails", "ContactDetailedInfo", None, {}),
        "POST_HISTORY": Route("POST", "/contacts/{contactId}/history", "ContactHistoryDataSourceLoadOptions", "ContactHistoryInfo", {}),
        "POST_MERGE_PREVIEW": Route("POST", "/contacts/{mergeToId}/merge/preview", "MergeContactsPreviewRequestModel", "MergeContactsPreviewInfo", {}),
        "POST_SEARCH": Route("POST", "/contacts/search", "WebApiDataSourceLoadOptions", None, {}),
        "POST_V2_SEARCH": Route("POST", "/contacts/v2/search", "MergeContactsSearchRequestModel", "List[SearchContactEntityResult]", {}),
        "PUT_EDITDETAILS": Route("PUT", "/contacts/{contactId}/editdetails", "ContactDetailedInfo", None, {}),
        "PUT_MERGE": Route("PUT", "/contacts/{mergeToId}/merge", "MergeContactsRequestModel", None, {}),
    },
    "DASHBOARD": {
        "GET": Route("GET", "/dashboard", None, None, {}),
        "GET_GRIDVIEWS": Route("GET", "/dashboard/gridviews", None, None, {}),
        "GET_GRIDVIEWSTATE": Route("GET", "/dashboard/gridviewstate/{id}", None, None, {}),
        "POST_GRIDVIEWSTATE": Route("POST", "/dashboard/gridviewstate/{id}", None, None, {}),
        "POST_INBOUND": Route("POST", "/dashboard/inbound", "WebApiDataSourceLoadOptions", "List[AgentInboundViewRecord]", {}),
        "POST_INHOUSE": Route("POST", "/dashboard/inhouse", "WebApiDataSourceLoadOptions", "List[AgentInhouseViewRecord]", {}),
        "POST_LOCAL_DELIVERIES": Route("POST", "/dashboard/local-deliveries", "WebApiDataSourceLoadOptions", "List[AgentLocalDeliveriesViewRecord]", {}),
        "POST_OUTBOUND": Route("POST", "/dashboard/outbound", "WebApiDataSourceLoadOptions", "List[AgentOutboundViewRecord]", {}),
        "POST_RECENTESTIMATES": Route("POST", "/dashboard/recentestimates", "WebApiDataSourceLoadOptions", "List[AgentRecentEstimatesViewRecord]", {}),
    },
    "DOCUMENTS": {
        "GET_GET": Route("GET", "/documents/get/{docPath}", None, None, {}),
        "GET_GET_THUMBNAIL": Route("GET", "/documents/get/thumbnail/{docPath}", None, None, {}),
        "GET_LIST": Route("GET", "/documents/list", None, None, {}),
        "POST": Route("POST", "/documents", None, None, {}),
        "PUT_HIDE": Route("PUT", "/documents/hide/{docId}", None, None, {}),
        "PUT_UPDATE": Route("PUT", "/documents/update/{docId}", "DocumentUpdateModel", None, {}),
    },
    "E_SIGN": {
        "GET": Route("GET", "/e-sign/{jobDisplayId}/{bookingKey}", None, None, {}),
        "GET_RESULT": Route("GET", "/e-sign/result", None, None, {}),
    },
    "EMAIL": {
        "POST_LABELREQUEST": Route("POST", "/email/{jobDisplayId}/labelrequest", None, None, {}),
    },
    "JOB": {
        "DELETE_ONHOLD": Route("DELETE", "/job/{jobDisplayId}/onhold", None, None, {}),
        "DELETE_PARCELITEMS": Route("DELETE", "/job/{jobDisplayId}/parcelitems/{parcelItemId}", None, None, {}),
        "DELETE_SHIPMENT": Route("DELETE", "/job/{jobDisplayId}/shipment", "DeleteShipRequestModel", None, {}),
        "DELETE_SHIPMENT_ACCESSORIAL": Route("DELETE", "/job/{jobDisplayId}/shipment/accessorial/{addOnId}", None, None, {}),
        "DELETE_TIMELINE": Route("DELETE", "/job/{jobDisplayId}/timeline/{timelineTaskId}", None, "DeleteTaskResponse", {}),
        "GET": Route("GET", "/job/{jobDisplayId}", None, None, {}),
        "GET_CALENDARITEMS": Route("GET", "/job/{jobDisplayId}/calendaritems", None, None, {}),
        "GET_DOCUMENT_CONFIG": Route("GET", "/job/documentConfig", None, None, {}),
        "GET_FEEDBACK": Route("GET", "/job/feedback/{jobDisplayId}", None, None, {}),
        "GET_FORM_ADDRESS_LABEL": Route("GET", "/job/{jobDisplayId}/form/address-label", None, None, {}),
        "GET_FORM_BILL_OF_LADING": Route("GET", "/job/{jobDisplayId}/form/bill-of-lading", None, None, {}),
        "GET_FORM_CREDIT_CARD_AUTHORIZATION": Route("GET", "/job/{jobDisplayId}/form/credit-card-authorization", None, None, {}),
        "GET_FORM_CUSTOMER_QUOTE": Route("GET", "/job/{jobDisplayId}/form/customer-quote", None, None, {}),
        "GET_FORM_INVOICE": Route("GET", "/job/{jobDisplayId}/form/invoice", None, None, {}),
        "GET_FORM_INVOICE_EDITABLE": Route("GET", "/job/{jobDisplayId}/form/invoice/editable", None, "USAREditableFormResponseModel", {}),
        "GET_FORM_ITEM_LABELS": Route("GET", "/job/{jobDisplayId}/form/item-labels", None, None, {}),
        "GET_FORM_OPERATIONS": Route("GET", "/job/{jobDisplayId}/form/operations", None, None, {}),
        "GET_FORM_PACKAGING_LABELS": Route("GET", "/job/{jobDisplayId}/form/packaging-labels", None, None, {}),
        "GET_FORM_PACKAGING_SPECIFICATION": Route("GET", "/job/{jobDisplayId}/form/packaging-specification", None, None, {}),
        "GET_FORM_PACKING_SLIP": Route("GET", "/job/{jobDisplayId}/form/packing-slip", None, None, {}),
        "GET_FORM_QUICK_SALE": Route("GET", "/job/{jobDisplayId}/form/quick-sale", None, None, {}),
        "GET_FORM_SHIPMENTS": Route("GET", "/job/{jobDisplayId}/form/shipments", None, "List[FormsShipmentPlan]", {}),
        "GET_FORM_USAR": Route("GET", "/job/{jobDisplayId}/form/usar", None, None, {}),
        "GET_FORM_USAR_EDITABLE": Route("GET", "/job/{jobDisplayId}/form/usar/editable", None, "USAREditableFormResponseModel", {}),
        "GET_FREIGHTPROVIDERS": Route("GET", "/job/{jobDisplayId}/freightproviders", None, "List[PricedFreightProvider]", {}),
        "GET_JOB_ACCESS_LEVEL": Route("GET", "/job/jobAccessLevel", None, None, {}),
        "GET_NOTE": Route("GET", "/job/{jobDisplayId}/note/{id}", None, "JobTaskNote", {}),
        "GET_ONHOLD": Route("GET", "/job/{jobDisplayId}/onhold/{id}", None, "OnHoldDetails", {}),
        "GET_ONHOLD_FOLLOWUPUSER": Route("GET", "/job/{jobDisplayId}/onhold/followupuser/{contactId}", None, "OnHoldUser", {}),
        "GET_ONHOLD_FOLLOWUPUSERS": Route("GET", "/job/{jobDisplayId}/onhold/followupusers", None, "List[OnHoldUser]", {}),
        "GET_PACKAGINGCONTAINERS": Route("GET", "/job/{jobDisplayId}/packagingcontainers", None, "List[Packaging]", {}),
        "GET_PARCELITEMS": Route("GET", "/job/{jobDisplayId}/parcelitems", None, "List[ParcelItemWithPackage]", {}),
        "GET_PARCEL_ITEMS_WITH_MATERIALS": Route("GET", "/job/{jobDisplayId}/parcel-items-with-materials", None, "List[ParcelItemWithMaterials]", {}),
        "GET_PAYMENT": Route("GET", "/job/{jobDisplayId}/payment", None, None, {}),
        "GET_PAYMENT_CREATE": Route("GET", "/job/{jobDisplayId}/payment/create", None, None, {}),
        "GET_PAYMENT_SOURCES": Route("GET", "/job/{jobDisplayId}/payment/sources", None, None, {}),
        "GET_PRICE": Route("GET", "/job/{jobDisplayId}/price", None, None, {}),
        "GET_RFQ": Route("GET", "/job/{jobDisplayId}/rfq", None, "List[QuoteRequestDisplayInfo]", {}),
        "GET_RFQ_STATUSOF_FORCOMPANY": Route("GET", "/job/{jobDisplayId}/rfq/statusof/{rfqServiceType}/forcompany/{companyId}", None, "QuoteRequestStatus", {}),
        "GET_SEARCH": Route("GET", "/job/search", None, None, {}),
        "GET_SHIPMENT_ACCESSORIALS": Route("GET", "/job/{jobDisplayId}/shipment/accessorials", None, "List[JobParcelAddOn]", {}),
        "GET_SHIPMENT_EXPORTDATA": Route("GET", "/job/{jobDisplayId}/shipment/exportdata", None, None, {}),
        "GET_SHIPMENT_ORIGINDESTINATION": Route("GET", "/job/{jobDisplayId}/shipment/origindestination", None, "ShipmentOriginDestination", {}),
        "GET_SHIPMENT_RATEQUOTES": Route("GET", "/job/{jobDisplayId}/shipment/ratequotes", None, "JobCarrierRatesModel", {}),
        "GET_SHIPMENT_RATESSTATE": Route("GET", "/job/{jobDisplayId}/shipment/ratesstate", None, None, {}),
        "GET_SMS": Route("GET", "/job/{jobDisplayId}/sms", None, None, {}),
        "GET_SMS_TEMPLATEBASED": Route("GET", "/job/{jobDisplayId}/sms/templatebased/{templateId}", None, None, {}),
        "GET_SUBMANAGEMENTSTATUS": Route("GET", "/job/{jobDisplayId}/submanagementstatus", None, None, {}),
        "GET_TIMELINE": Route("GET", "/job/{jobDisplayId}/timeline/{timelineTaskIdentifier}", None, "CarrierTask", {}),
        "GET_TIMELINE_AGENT": Route("GET", "/job/{jobDisplayId}/timeline/{taskCode}/agent", None, "CompanyListItem", {}),
        "GET_TRACKING": Route("GET", "/job/{jobDisplayId}/tracking", None, None, {}),
        "GET_TRACKING_SHIPMENT": Route("GET", "/job/{jobDisplayId}/tracking/shipment/{proNumber}", None, "ShipmentTrackingDetails", {}),
        "GET_UPDATE_PAGE_CONFIG": Route("GET", "/job/{jobDisplayId}/updatePageConfig", None, "JobUpdatePageConfig", {}),
        "PATCH_TIMELINE": Route("PATCH", "/job/{jobDisplayId}/timeline/{timelineTaskId}", "UpdateTaskModel", None, {}),
        "POST": Route("POST", "/job", "JobSaveRequestModel", None, {}),
        "POST_BOOK": Route("POST", "/job/{jobDisplayId}/book", None, None, {}),
        "POST_CHANGE_AGENT": Route("POST", "/job/{jobDisplayId}/changeAgent", "ChangeJobAgentRequest", None, {}),
        "POST_EMAIL": Route("POST", "/job/{jobDisplayId}/email", "SendDocumentEmailModel", None, {}),
        "POST_EMAIL_CREATETRANSACTIONALEMAIL": Route("POST", "/job/{jobDisplayId}/email/createtransactionalemail", None, None, {}),
        "POST_EMAIL_SEND": Route("POST", "/job/{jobDisplayId}/email/{emailTemplateGuid}/send", None, None, {}),
        "POST_EMAIL_SENDDOCUMENT": Route("POST", "/job/{jobDisplayId}/email/senddocument", "SendDocumentEmailModel", None, {}),
        "POST_FEEDBACK": Route("POST", "/job/feedback/{jobDisplayId}", "FeedbackSaveModel", None, {}),
        "POST_FREIGHTITEMS": Route("POST", "/job/{jobDisplayId}/freightitems", "SaveAllFreightItemsRequest", None, {}),
        "POST_FREIGHTPROVIDERS": Route("POST", "/job/{jobDisplayId}/freightproviders", None, "ServiceBaseResponse", {}),
        "POST_FREIGHTPROVIDERS_RATEQUOTE": Route("POST", "/job/{jobDisplayId}/freightproviders/{optionIndex}/ratequote", "SetRateModel", "ServiceBaseResponse", {}),
        "POST_ITEM_NOTES": Route("POST", "/job/{jobDisplayId}/item/notes", "JobItemNotesData", None, {}),
        "POST_NOTE": Route("POST", "/job/{jobDisplayId}/note", "TaskNoteModel", "JobTaskNote", {}),
        "POST_ONHOLD": Route("POST", "/job/{jobDisplayId}/onhold", "SaveOnHoldRequest", "SaveOnHoldResponse", {}),
        "POST_ONHOLD_COMMENT": Route("POST", "/job/{jobDisplayId}/onhold/{onHoldId}/comment", None, "OnHoldNoteDetails", {}),
        "POST_PARCELITEMS": Route("POST", "/job/{jobDisplayId}/parcelitems", "SaveAllParcelItemsRequest", "List[ParcelItemWithPackage]", {}),
        "POST_PAYMENT_ACHCREDIT_TRANSFER": Route("POST", "/job/{jobDisplayId}/payment/ACHCreditTransfer", None, None, {}),
        "POST_PAYMENT_ACHPAYMENT_SESSION": Route("POST", "/job/{jobDisplayId}/payment/ACHPaymentSession", None, None, {}),
        "POST_PAYMENT_ATTACH_CUSTOMER_BANK": Route("POST", "/job/{jobDisplayId}/payment/attachCustomerBank", "AttachCustomerBankModel", None, {}),
        "POST_PAYMENT_BANKSOURCE": Route("POST", "/job/{jobDisplayId}/payment/banksource", "PaymentSourceDetails", None, {}),
        "POST_PAYMENT_BYSOURCE": Route("POST", "/job/{jobDisplayId}/payment/bysource", None, None, {}),
        "POST_PAYMENT_CANCEL_JOB_ACHVERIFICATION": Route("POST", "/job/{jobDisplayId}/payment/cancelJobACHVerification", None, None, {}),
        "POST_PAYMENT_VERIFY_JOB_ACHSOURCE": Route("POST", "/job/{jobDisplayId}/payment/verifyJobACHSource", "VerifyBankAccountRequest", None, {}),
        "POST_SEARCH_BY_DETAILS": Route("POST", "/job/searchByDetails", "SearchJobFilter", None, {}),
        "POST_SHIPMENT_ACCESSORIAL": Route("POST", "/job/{jobDisplayId}/shipment/accessorial", "JobParcelAddOn", None, {}),
        "POST_SHIPMENT_BOOK": Route("POST", "/job/{jobDisplayId}/shipment/book", "BookShipmentRequest", None, {}),
        "POST_SHIPMENT_EXPORTDATA": Route("POST", "/job/{jobDisplayId}/shipment/exportdata", "InternationalParams", None, {}),
        "POST_SHIPMENT_RATEQUOTES": Route("POST", "/job/{jobDisplayId}/shipment/ratequotes", "TransportationRatesRequestModel", "JobCarrierRatesModel", {}),
        "POST_SMS": Route("POST", "/job/{jobDisplayId}/sms", "SendSMSModel", None, {}),
        "POST_SMS_READ": Route("POST", "/job/{jobDisplayId}/sms/read", "MarkSmsAsReadModel", None, {}),
        "POST_STATUS_QUOTE": Route("POST", "/job/{jobDisplayId}/status/quote", None, None, {}),
        "POST_TIMELINE": Route("POST", "/job/{jobDisplayId}/timeline", "TimelineTaskInput", "SaveResponseModel", {}),
        "POST_TIMELINE_INCREMENTJOBSTATUS": Route("POST", "/job/{jobDisplayId}/timeline/incrementjobstatus", "IncrementJobStatusInputModel", "IncrementJobStatusResponseModel", {}),
        "POST_TIMELINE_UNDOINCREMENTJOBSTATUS": Route("POST", "/job/{jobDisplayId}/timeline/undoincrementjobstatus", None, None, {}),
        "POST_TRANSFER": Route("POST", "/job/transfer/{jobDisplayId}", "TransferModel", None, {}),
        "PUT_ITEM": Route("PUT", "/job/{jobDisplayId}/item/{itemId}", "JobItemInfoData", None, {}),
        "PUT_NOTE": Route("PUT", "/job/{jobDisplayId}/note/{id}", "TaskNoteModel", None, {}),
        "PUT_ONHOLD": Route("PUT", "/job/{jobDisplayId}/onhold/{onHoldId}", "SaveOnHoldRequest", "SaveOnHoldResponse", {}),
        "PUT_ONHOLD_DATES": Route("PUT", "/job/{jobDisplayId}/onhold/{onHoldId}/dates", "SaveOnHoldDatesModel", "ResolveJobOnHoldResponse", {}),
        "PUT_ONHOLD_RESOLVE": Route("PUT", "/job/{jobDisplayId}/onhold/{onHoldId}/resolve", "SaveOnHoldRequest", "ResolveJobOnHoldResponse", {}),
        "PUT_SAVE": Route("PUT", "/job/save", "JobSaveRequest", None, {}),
    },
    "JOBINTACCT": {
        "DELETE": Route("DELETE", "/jobintacct/{jobDisplayId}/{franchiseeId}", None, None, {}),
        "GET": Route("GET", "/jobintacct/{jobDisplayId}", None, None, {}),
        "POST": Route("POST", "/jobintacct/{jobDisplayId}", "CreateJobIntacctModel", None, {}),
        "POST_APPLY_REBATE": Route("POST", "/jobintacct/{jobDisplayId}/applyRebate", None, None, {}),
        "POST_DRAFT": Route("POST", "/jobintacct/{jobDisplayId}/draft", "CreateJobIntacctModel", None, {}),
    },
    "LOOKUP": {
        "GET": Route("GET", "/lookup/{masterConstantKey}/{valueId}", None, None, {}),
        "GET_ACCESS_KEY": Route("GET", "/lookup/accessKey/{accessKey}", None, None, {}),
        "GET_ACCESS_KEYS": Route("GET", "/lookup/accessKeys", None, None, {}),
        "GET_COMON_INSURANCE": Route("GET", "/lookup/comonInsurance", None, None, {}),
        "GET_CONTACT_TYPES": Route("GET", "/lookup/contactTypes", None, "List[ContactTypeEntity]", {}),
        "GET_COUNTRIES": Route("GET", "/lookup/countries", None, "List[CountryCodeDto]", {}),
        "GET_DENSITY_CLASS_MAP": Route("GET", "/lookup/densityClassMap", None, "List[GuidSequentialRangeValue]", {}),
        "GET_DOCUMENT_TYPES": Route("GET", "/lookup/documentTypes", None, None, {}),
        "GET_ITEMS": Route("GET", "/lookup/items", None, None, {}),
        "GET_PARCEL_PACKAGE_TYPES": Route("GET", "/lookup/parcelPackageTypes", None, None, {}),
        "GET_PPCCAMPAIGNS": Route("GET", "/lookup/PPCCampaigns", None, None, {}),
        "GET_REFER_CATEGORY": Route("GET", "/lookup/referCategory", None, None, {}),
        "GET_REFER_CATEGORY_HEIRACHY": Route("GET", "/lookup/referCategoryHeirachy", None, None, {}),
        "GET_RESET_MASTER_CONSTANT_CACHE": Route("GET", "/lookup/resetMasterConstantCache", None, None, {}),
    },
    "NOTE": {
        "GET": Route("GET", "/note", None, "List[Notes]", {}),
        "GET_SUGGEST_USERS": Route("GET", "/note/suggestUsers", None, "List[SuggestedContactEntity]", {}),
        "POST": Route("POST", "/note", "NoteModel", "Notes", {}),
        "PUT": Route("PUT", "/note/{id}", "NoteModel", None, {}),
    },
    "NOTIFICATIONS": {
        "GET": Route("GET", "/notifications", None, None, {}),
    },
    "PARTNER": {
        "GET": Route("GET", "/partner", None, "List[Partner]", {}),
        "POST_SEARCH": Route("POST", "/partner/search", "SearchPartnersDataSourceLoadOptions", "List[Partner]", {}),
    },
    "REPORTS": {
        "POST_INSURANCE": Route("POST", "/reports/insurance", "InsuranceReportRequest", "InsuranceReport", {}),
        "POST_REFERRED_BY": Route("POST", "/reports/referredBy", "ReferredByReportRequest", "ReferredByReport", {}),
        "POST_SALES": Route("POST", "/reports/sales", "SalesForecastReportRequest", "SalesForecastReport", {}),
        "POST_SALES_DRILLDOWN": Route("POST", "/reports/salesDrilldown", "Web2LeadRevenueFilter", None, {}),
        "POST_SALES_SUMMARY": Route("POST", "/reports/sales/summary", "SalesForecastSummaryRequest", "SalesForecastSummary", {}),
        "POST_TOP_REVENUE_CUSTOMERS": Route("POST", "/reports/topRevenueCustomers", "Web2LeadRevenueFilter", "RevenueCustomer", {}),
        "POST_TOP_REVENUE_SALES_REPS": Route("POST", "/reports/topRevenueSalesReps", "Web2LeadRevenueFilter", "RevenueCustomer", {}),
        "POST_WEB2_LEAD": Route("POST", "/reports/web2Lead", "Web2LeadV2RequestModel", "Web2LeadReport", {}),
    },
    "RFQ": {
        "GET": Route("GET", "/rfq/{rfqId}", None, None, {}),
        "GET_FORJOB": Route("GET", "/rfq/forjob/{jobId}", None, None, {}),
        "POST_ACCEPT": Route("POST", "/rfq/{rfqId}/accept", "AcceptModel", None, {}),
        "POST_ACCEPTWINNER": Route("POST", "/rfq/{rfqId}/acceptwinner", None, None, {}),
        "POST_CANCEL": Route("POST", "/rfq/{rfqId}/cancel", None, None, {}),
        "POST_COMMENT": Route("POST", "/rfq/{rfqId}/comment", None, None, {}),
        "POST_DECLINE": Route("POST", "/rfq/{rfqId}/decline", None, None, {}),
    },
    "SHIPMENT": {
        "GET": Route("GET", "/shipment", None, "ShipmentDetails", {}),
        "GET_ACCESSORIALS": Route("GET", "/shipment/accessorials", None, None, {}),
        "GET_DOCUMENT": Route("GET", "/shipment/document/{docId}", None, "ShippingDocument", {}),
    },
    "SMSTEMPLATE": {
        "DELETE": Route("DELETE", "/SmsTemplate/{templateId}", None, None, {}),
        "GET": Route("GET", "/SmsTemplate/{templateId}", None, None, {}),
        "GET_JOB_STATUSES": Route("GET", "/SmsTemplate/jobStatuses", None, None, {}),
        "GET_LIST": Route("GET", "/SmsTemplate/list", None, None, {}),
        "GET_NOTIFICATION_TOKENS": Route("GET", "/SmsTemplate/notificationTokens", None, None, {}),
        "POST_SAVE": Route("POST", "/SmsTemplate/save", "SmsTemplateModel", None, {}),
    },
    "USERS": {
        "GET_POCUSERS": Route("GET", "/users/pocusers", None, None, {}),
        "GET_ROLES": Route("GET", "/users/roles", None, None, {}),
        "POST_LIST": Route("POST", "/users/list", "WebApiDataSourceLoadOptions", None, {}),
        "POST_USER": Route("POST", "/users/user", "CreateUserModel", None, {}),
        "PUT_USER": Route("PUT", "/users/user", "UserInfo", None, {}),
    },
    "V2": {
        "GET_JOB_TRACKING": Route("GET", "/v2/job/{jobDisplayId}/tracking/{historyAmount}", None, None, {}),
    },
    "V3": {
        "GET_JOB_TRACKING": Route("GET", "/v3/job/{jobDisplayId}/tracking/{historyAmount}", None, "JobTrackingResponseV3", {}),
    },
    "VALUES": {
        "GET": Route("GET", "/Values", None, None, {}),
    },
    "VIEWS": {
        "DELETE": Route("DELETE", "/views/{viewId}", None, None, {}),
        "GET": Route("GET", "/views/{viewId}", None, None, {}),
        "GET_ACCESSINFO": Route("GET", "/views/{viewId}/accessinfo", None, None, {}),
        "GET_ALL": Route("GET", "/views/all", None, None, {}),
        "GET_DATASETSP": Route("GET", "/views/datasetsp/{spName}", None, None, {}),
        "GET_DATASETSPS": Route("GET", "/views/datasetsps", None, None, {}),
        "POST": Route("POST", "/views", "GridViewDetails", None, {}),
        "PUT_ACCESS": Route("PUT", "/views/{viewId}/access", None, None, {}),
    },
    "WEBHOOKS": {
        "POST_STRIPE_CHECKOUT_SESSION_COMPLETED": Route("POST", "/webhooks/stripe/checkout.session.completed", None, None, {}),
        "POST_STRIPE_CONNECT_HANDLE": Route("POST", "/webhooks/stripe/connect/handle", None, None, {}),
        "POST_STRIPE_HANDLE": Route("POST", "/webhooks/stripe/handle", None, None, {}),
        "POST_TWILIO_BODY_SMS_INBOUND": Route("POST", "/webhooks/twilio/body-sms-inbound", "TwilioInboundMessageWebhookModel", None, {}),
        "POST_TWILIO_FORM_SMS_INBOUND": Route("POST", "/webhooks/twilio/form-sms-inbound", None, None, {}),
        "POST_TWILIO_SMS_STATUS_CALLBACK": Route("POST", "/webhooks/twilio/smsStatusCallback", None, None, {}),
    },
}


__all__ = ["SCHEMA", "Route"]
