"""Schema mappings auto-generated from ACPortal_709_swagger.json.

DO NOT EDIT MANUALLY - regenerate with:
    python generate_schema_mappings.py

This module provides mappings from API endpoints to their corresponding
Pydantic model names for request validation and response casting.
"""

from typing import Dict, List, Tuple, Union


# Request body schema mappings
# Format: (HTTP_METHOD, path_pattern) -> model_name
REQUEST_MAPPINGS: Dict[Tuple[str, str], str] = {
    ('DELETE', '/api/job/{jobDisplayId}/shipment'): 'DeleteShipRequestModel',
    ('PATCH', '/api/job/{jobDisplayId}/timeline/{timelineTaskId}'): 'UpdateTaskModel',
    ('POST', '/api/SmsTemplate/save'): 'SmsTemplateModel',
    ('POST', '/api/account/confirm'): 'ConfirmEmailModel',
    ('POST', '/api/account/forgot'): 'ForgotLoginModel',
    ('POST', '/api/account/register'): 'RegistrationModel',
    ('POST', '/api/account/resetpassword'): 'ResetPasswordModel',
    ('POST', '/api/account/setpassword'): 'ChangePasswordModel',
    ('POST', '/api/address/{addressId}/validated'): 'SaveValidatedRequest',
    ('POST', '/api/admin/advancedsettings'): 'AdvancedSettingsEntitySaveModel',
    ('POST', '/api/admin/carriererrormessage'): 'CarrierErrorMessage',
    ('POST', '/api/admin/globalsettings/getinsuranceexceptions'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/admin/globalsettings/intacct'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/commodity'): 'AddCommodityModel',
    ('POST', '/api/commodity-map'): 'AddCommodityMapModel',
    ('POST', '/api/commodity-map/search'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/commodity/search'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/commodity/suggestions'): 'GetCommoditySuggestionsDataSourceLoadOptions',
    ('POST', '/api/companies/filteredCustomers'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/companies/fulldetails'): 'CompanyDetails',
    ('POST', '/api/companies/list'): 'TagBoxDataSourceLoadOptions',
    ('POST', '/api/companies/search/v2'): 'SearchCompanyDataSourceLoadOptions',
    ('POST', '/api/companies/simplelist'): 'TagBoxDataSourceLoadOptions',
    ('POST', '/api/companies/{companyId}/capabilities'): 'CommercialCapabilities',
    ('POST', '/api/companies/{companyId}/carrierAcounts'): 'UpdateCarrierAccountsModel',
    ('POST', '/api/companies/{companyId}/geosettings'): 'SaveGeoSettingModel',
    ('POST', '/api/companies/{companyId}/packaginglabor'): 'PackagingLaborSettings',
    ('POST', '/api/companies/{companyId}/packagingsettings'): 'PackagingTariffSettings',
    ('POST', '/api/company/{companyId}/containerthicknessinches'): 'ContainerThickness',
    ('POST', '/api/company/{companyId}/gridsettings'): 'SaveGridSettingsModel',
    ('POST', '/api/company/{companyId}/material'): 'SaveCompanyMaterialModel',
    ('POST', '/api/company/{companyId}/truck'): 'SaveTruckRequest',
    ('POST', '/api/contacts/customers'): 'SearchContactRequest',
    ('POST', '/api/contacts/editdetails'): 'ContactDetailedInfo',
    ('POST', '/api/contacts/search'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/contacts/v2/search'): 'MergeContactsSearchRequestModel',
    ('POST', '/api/contacts/{contactId}/history'): 'ContactHistoryDataSourceLoadOptions',
    ('POST', '/api/contacts/{mergeToId}/merge/preview'): 'MergeContactsPreviewRequestModel',
    ('POST', '/api/dashboard/inbound'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/dashboard/inhouse'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/dashboard/local-deliveries'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/dashboard/outbound'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/dashboard/recentestimates'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/job'): 'JobSaveRequestModel',
    ('POST', '/api/job/feedback/{jobDisplayId}'): 'FeedbackSaveModel',
    ('POST', '/api/job/searchByDetails'): 'SearchJobFilter',
    ('POST', '/api/job/transfer/{jobDisplayId}'): 'TransferModel',
    ('POST', '/api/job/{jobDisplayId}/changeAgent'): 'ChangeJobAgentRequest',
    ('POST', '/api/job/{jobDisplayId}/email'): 'SendDocumentEmailModel',
    ('POST', '/api/job/{jobDisplayId}/email/senddocument'): 'SendDocumentEmailModel',
    ('POST', '/api/job/{jobDisplayId}/freightitems'): 'SaveAllFreightItemsRequest',
    ('POST', '/api/job/{jobDisplayId}/freightproviders/{optionIndex}/ratequote'): 'SetRateModel',
    ('POST', '/api/job/{jobDisplayId}/item/notes'): 'JobItemNotesData',
    ('POST', '/api/job/{jobDisplayId}/note'): 'TaskNoteModel',
    ('POST', '/api/job/{jobDisplayId}/onhold'): 'SaveOnHoldRequest',
    ('POST', '/api/job/{jobDisplayId}/parcelitems'): 'SaveAllParcelItemsRequest',
    ('POST', '/api/job/{jobDisplayId}/payment/attachCustomerBank'): 'AttachCustomerBankModel',
    ('POST', '/api/job/{jobDisplayId}/payment/banksource'): 'PaymentSourceDetails',
    ('POST', '/api/job/{jobDisplayId}/payment/verifyJobACHSource'): 'VerifyBankAccountRequest',
    ('POST', '/api/job/{jobDisplayId}/shipment/accessorial'): 'JobParcelAddOn',
    ('POST', '/api/job/{jobDisplayId}/shipment/book'): 'BookShipmentRequest',
    ('POST', '/api/job/{jobDisplayId}/shipment/exportdata'): 'InternationalParams',
    ('POST', '/api/job/{jobDisplayId}/shipment/ratequotes'): 'TransportationRatesRequestModel',
    ('POST', '/api/job/{jobDisplayId}/sms'): 'SendSMSModel',
    ('POST', '/api/job/{jobDisplayId}/sms/read'): 'MarkSmsAsReadModel',
    ('POST', '/api/job/{jobDisplayId}/timeline'): 'BaseTaskModel',
    ('POST', '/api/job/{jobDisplayId}/timeline/incrementjobstatus'): 'IncrementJobStatusInputModel',
    ('POST', '/api/jobintacct/{jobDisplayId}'): 'CreateJobIntacctModel',
    ('POST', '/api/jobintacct/{jobDisplayId}/draft'): 'CreateJobIntacctModel',
    ('POST', '/api/note'): 'NoteModel',
    ('POST', '/api/partner/search'): 'SearchPartnersDataSourceLoadOptions',
    ('POST', '/api/reports/insurance'): 'InsuranceReportRequest',
    ('POST', '/api/reports/referredBy'): 'ReferredByReportRequest',
    ('POST', '/api/reports/sales'): 'SalesForecastReportRequest',
    ('POST', '/api/reports/sales/summary'): 'SalesForecastSummaryRequest',
    ('POST', '/api/reports/salesDrilldown'): 'Web2LeadRevenueFilter',
    ('POST', '/api/reports/topRevenueCustomers'): 'Web2LeadRevenueFilter',
    ('POST', '/api/reports/topRevenueSalesReps'): 'Web2LeadRevenueFilter',
    ('POST', '/api/reports/web2Lead'): 'Web2LeadV2RequestModel',
    ('POST', '/api/rfq/{rfqId}/accept'): 'AcceptModel',
    ('POST', '/api/users/list'): 'WebApiDataSourceLoadOptions',
    ('POST', '/api/users/user'): 'CreateUserModel',
    ('POST', '/api/views'): 'GridViewDetails',
    ('POST', '/api/webhooks/twilio/body-sms-inbound'): 'TwilioInboundMessageWebhookModel',
    ('PUT', '/api/commodity-map/{id}'): 'UpdateCommodityMapModel',
    ('PUT', '/api/commodity/{id}'): 'UpdateCommodityModel',
    ('PUT', '/api/companies/{companyId}/fulldetails'): 'CompanyDetails',
    ('PUT', '/api/company/{companyId}/material/{materialId}'): 'SaveCompanyMaterialModel',
    ('PUT', '/api/company/{companyId}/truck/{truckId}'): 'SaveTruckRequest',
    ('PUT', '/api/contacts/{contactId}/editdetails'): 'ContactDetailedInfo',
    ('PUT', '/api/contacts/{mergeToId}/merge'): 'MergeContactsRequestModel',
    ('PUT', '/api/documents/update/{docId}'): 'DocumentUpdateModel',
    ('PUT', '/api/job/save'): 'JobSaveRequest',
    ('PUT', '/api/job/{jobDisplayId}/item/{itemId}'): 'JobItemInfoData',
    ('PUT', '/api/job/{jobDisplayId}/note/{id}'): 'TaskNoteModel',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}'): 'SaveOnHoldRequest',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}/dates'): 'SaveOnHoldDatesModel',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}/resolve'): 'SaveOnHoldRequest',
    ('PUT', '/api/note/{id}'): 'NoteModel',
    ('PUT', '/api/users/user'): 'UserInfo',
}


# Response schema mappings
# Format: (HTTP_METHOD, path_pattern) -> model_name or [model_name] for arrays
RESPONSE_MAPPINGS: Dict[Tuple[str, str], Union[str, List[str]]] = {
    ('DELETE', '/api/commodity-map/{id}'): 'ServiceBaseResponse',
    ('DELETE', '/api/company/{companyId}/truck/{truckId}'): 'ServiceWarningResponse',
    ('DELETE', '/api/job/{jobDisplayId}/timeline/{timelineTaskId}'): 'DeleteTaskResponse',
    ('GET', '/api/address/isvalid'): 'AddressIsValidResult',
    ('GET', '/api/address/propertytype'): 'PropertyType',
    ('GET', '/api/admin/globalsettings/companyhierarchy'): 'CompanyHierarchyInfo',
    ('GET', '/api/admin/globalsettings/companyhierarchy/company/{companyId}'): 'CompanyHierarchyInfo',
    ('GET', '/api/commodity-map/{id}'): 'CommodityMapDetailsServiceResponse',
    ('GET', '/api/commodity/{id}'): 'CommodityWithParentsServiceResponse',
    ('GET', '/api/companies/suggest-carriers'): ['CarrierCompanyInfo'],
    ('GET', '/api/companies/{companyId}/franchiseeAddresses'): ['CompanyAddressInfo'],
    ('GET', '/api/companies/{companyId}/fulldetails'): 'CompanyDetails',
    ('GET', '/api/company/{companyId}/calendar/{date}'): 'Calendar',
    ('GET', '/api/company/{companyId}/calendar/{date}/baseinfo'): 'BaseInfoCalendar',
    ('GET', '/api/company/{companyId}/containerthicknessinches'): ['ContainerThickness'],
    ('GET', '/api/company/{companyId}/gridsettings'): 'GridSettingsEntity',
    ('GET', '/api/company/{companyId}/material'): ['CompanyMaterial'],
    ('GET', '/api/company/{companyId}/planner'): ['PlannerTask'],
    ('GET', '/api/company/{companyId}/setupdata'): 'CompanySetupData',
    ('GET', '/api/company/{companyId}/truck'): ['Truck'],
    ('GET', '/api/contacts/{contactId}/editdetails'): 'ContactDetailedInfo',
    ('GET', '/api/contacts/{contactId}/history/aggregated'): 'ContactHistoryAggregatedCost',
    ('GET', '/api/contacts/{contactId}/history/graphdata'): 'ContactHistoryGraphData',
    ('GET', '/api/contacts/{contactId}/primarydetails'): 'ContactPrimaryDetails',
    ('GET', '/api/job/{jobDisplayId}/form/invoice/editable'): 'USAREditableFormResponseModel',
    ('GET', '/api/job/{jobDisplayId}/form/shipments'): ['FormsShipmentPlan'],
    ('GET', '/api/job/{jobDisplayId}/form/usar/editable'): 'USAREditableFormResponseModel',
    ('GET', '/api/job/{jobDisplayId}/freightproviders'): ['PricedFreightProvider'],
    ('GET', '/api/job/{jobDisplayId}/note'): ['JobTaskNote'],
    ('GET', '/api/job/{jobDisplayId}/note/{id}'): 'JobTaskNote',
    ('GET', '/api/job/{jobDisplayId}/onhold'): ['ExtendedOnHoldInfo'],
    ('GET', '/api/job/{jobDisplayId}/onhold/followupuser/{contactId}'): 'OnHoldUser',
    ('GET', '/api/job/{jobDisplayId}/onhold/followupusers'): ['OnHoldUser'],
    ('GET', '/api/job/{jobDisplayId}/onhold/{id}'): 'OnHoldDetails',
    ('GET', '/api/job/{jobDisplayId}/packagingcontainers'): ['Packaging'],
    ('GET', '/api/job/{jobDisplayId}/parcel-items-with-materials'): ['ParcelItemWithMaterials'],
    ('GET', '/api/job/{jobDisplayId}/parcelitems'): ['ParcelItemWithPackage'],
    ('GET', '/api/job/{jobDisplayId}/rfq'): ['QuoteRequestDisplayInfo'],
    ('GET', '/api/job/{jobDisplayId}/rfq/statusof/{rfqServiceType}/forcompany/{companyId}'): 'QuoteRequestStatus',
    ('GET', '/api/job/{jobDisplayId}/shipment/accessorials'): ['JobParcelAddOn'],
    ('GET', '/api/job/{jobDisplayId}/shipment/origindestination'): 'ShipmentOriginDestination',
    ('GET', '/api/job/{jobDisplayId}/shipment/ratequotes'): 'JobCarrierRatesModel',
    ('GET', '/api/job/{jobDisplayId}/timeline'): 'TimelineResponse',
    ('GET', '/api/job/{jobDisplayId}/timeline/{taskCode}/agent'): 'CompanyListItem',
    ('GET', '/api/job/{jobDisplayId}/timeline/{timelineTaskIdentifier}'): 'CarrierTask',
    ('GET', '/api/job/{jobDisplayId}/tracking/shipment/{proNumber}'): 'ShipmentTrackingDetails',
    ('GET', '/api/job/{jobDisplayId}/updatePageConfig'): 'JobUpdatePageConfig',
    ('GET', '/api/lookup/contactTypes'): ['ContactTypeEntity'],
    ('GET', '/api/lookup/countries'): ['CountryCodeDto'],
    ('GET', '/api/lookup/densityClassMap'): ['GuidSequentialRangeValue'],
    ('GET', '/api/note'): ['Notes'],
    ('GET', '/api/note/suggestUsers'): ['SuggestedContactEntity'],
    ('GET', '/api/partner'): ['Partner'],
    ('GET', '/api/partner/{id}'): 'PartnerServiceResponse',
    ('GET', '/api/shipment'): 'ShipmentDetails',
    ('GET', '/api/shipment/document/{docId}'): 'ShippingDocument',
    ('GET', '/api/v3/job/{jobDisplayId}/tracking/{historyAmount}'): 'JobTrackingResponseV3',
    ('POST', '/api/admin/globalsettings/getinsuranceexceptions'): ['SelectApproveInsuranceResult'],
    ('POST', '/api/commodity'): 'CommodityServiceResponse',
    ('POST', '/api/commodity-map'): 'CommodityMapServiceResponse',
    ('POST', '/api/commodity-map/search'): ['CommodityMapDetails'],
    ('POST', '/api/commodity/search'): ['CommodityDetails'],
    ('POST', '/api/commodity/suggestions'): ['CommodityWithParents'],
    ('POST', '/api/companies/search/v2'): ['SearchCompanyResponse'],
    ('POST', '/api/company/{companyId}/material'): 'CompanyMaterial',
    ('POST', '/api/company/{companyId}/truck'): 'SaveEntityResponse',
    ('POST', '/api/contacts/v2/search'): ['SearchContactEntityResult'],
    ('POST', '/api/contacts/{contactId}/history'): 'ContactHistoryInfo',
    ('POST', '/api/contacts/{mergeToId}/merge/preview'): 'MergeContactsPreviewInfo',
    ('POST', '/api/dashboard/inbound'): ['AgentInboundViewRecord'],
    ('POST', '/api/dashboard/inhouse'): ['AgentInhouseViewRecord'],
    ('POST', '/api/dashboard/local-deliveries'): ['AgentLocalDeliveriesViewRecord'],
    ('POST', '/api/dashboard/outbound'): ['AgentOutboundViewRecord'],
    ('POST', '/api/dashboard/recentestimates'): ['AgentRecentEstimatesViewRecord'],
    ('POST', '/api/job/{jobDisplayId}/freightproviders'): 'ServiceBaseResponse',
    ('POST', '/api/job/{jobDisplayId}/freightproviders/{optionIndex}/ratequote'): 'ServiceBaseResponse',
    ('POST', '/api/job/{jobDisplayId}/note'): 'JobTaskNote',
    ('POST', '/api/job/{jobDisplayId}/onhold'): 'SaveOnHoldResponse',
    ('POST', '/api/job/{jobDisplayId}/onhold/{onHoldId}/comment'): 'OnHoldNoteDetails',
    ('POST', '/api/job/{jobDisplayId}/parcelitems'): ['ParcelItemWithPackage'],
    ('POST', '/api/job/{jobDisplayId}/shipment/ratequotes'): 'JobCarrierRatesModel',
    ('POST', '/api/job/{jobDisplayId}/timeline'): 'SaveResponseModel',
    ('POST', '/api/job/{jobDisplayId}/timeline/incrementjobstatus'): 'IncrementJobStatusResponseModel',
    ('POST', '/api/note'): 'Notes',
    ('POST', '/api/partner/search'): ['Partner'],
    ('POST', '/api/reports/insurance'): 'InsuranceReport',
    ('POST', '/api/reports/referredBy'): 'ReferredByReport',
    ('POST', '/api/reports/sales'): 'SalesForecastReport',
    ('POST', '/api/reports/sales/summary'): 'SalesForecastSummary',
    ('POST', '/api/reports/topRevenueCustomers'): 'RevenueCustomer',
    ('POST', '/api/reports/topRevenueSalesReps'): 'RevenueCustomer',
    ('POST', '/api/reports/web2Lead'): 'Web2LeadReport',
    ('PUT', '/api/commodity-map/{id}'): 'CommodityMapServiceResponse',
    ('PUT', '/api/commodity/{id}'): 'CommodityServiceResponse',
    ('PUT', '/api/companies/{companyId}/fulldetails'): 'CompanyDetails',
    ('PUT', '/api/company/{companyId}/material/{materialId}'): 'CompanyMaterial',
    ('PUT', '/api/company/{companyId}/truck/{truckId}'): 'SaveEntityResponse',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}'): 'SaveOnHoldResponse',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}/dates'): 'ResolveJobOnHoldResponse',
    ('PUT', '/api/job/{jobDisplayId}/onhold/{onHoldId}/resolve'): 'ResolveJobOnHoldResponse',
}


# All models referenced in mappings (for validation)
ALL_REFERENCED_MODELS = set()
for model in REQUEST_MAPPINGS.values():
    ALL_REFERENCED_MODELS.add(model)
for model in RESPONSE_MAPPINGS.values():
    if isinstance(model, list):
        ALL_REFERENCED_MODELS.update(model)
    else:
        ALL_REFERENCED_MODELS.add(model)
