name: Python Package CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade Pip & Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest
          pip install .

      # - name: Run Tests
      #   run: pytest

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    permissions:
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Remove Old Build Artifacts
        run: rm -rf dist build ABConnect.egg-info

      - name: Install Build Tools
        run: python -m pip install --upgrade build twine

      - name: Build Package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
